## Ansible ##

ansible_become_pass: '{{ vault.ansible.ansible_become_pass }}'

roles_enabled:
  git: true
  zsh: true
  ssh: true
  services: true
  scripts: true
  gnupg: true
  conky: false

## git ##

git_signingKey: "GIT_SIGNING_KEY"

## conky ##

conky_email_username: '{{ vault.conky.email.user }}'
conky_email_password: '{{ vault.conky.email.password }}'
