## Ansible ##

ansible_become_pass: '{{ vault.ansible.ansible_become_pass }}'

## git ##

git_signingKey: "7B5B7705610BD2A7"

## conky ##

conky_email_username: '{{ vault.conky.email.user }}'
conky_email_password: '{{ vault.conky.email.password }}'
