---
    
## conky role ##

- name: Ensure directory structure exists
  file:
    path: '~{{ user_name }}/{{ item.path }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rwx,g=rx,o=rx
  with_filetree: '{{ templates_source }}/conky/shared'
  when:
    - item.state == 'directory'
    - item.path != '.git'
    - item.path != '.config'

- name: Ensure configs are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '~{{ user_name }}/{{ item.path | regex_replace("\.j2", "") }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rwx,g=rx,o=r
  with_filetree: '{{ templates_source }}/conky/shared'
  when:
    - item.state == 'file'
    - item.path != '.git'

- name: Ensure conkyrc populated from template
  copy:
    src: "{{ templates_source }}/conky/{{ ansible_facts['nodename'] }}.conkyrc"
    dest: '~{{ user_name }}/.config/conky/conkyrc'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rwx,g=rx,o=r
