---
  
- name: Ensure directory structure exists
  file:
    path: '~{{user_name}}/{{ item.path }}'
    state: directory
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: a-x,u=rwX,g=rwX,o=rX
  with_filetree: '{{ templates_source }}/oh-my-zsh'
  when:
    - item.state == 'directory'
    - item.path != '.git'

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '~{{ user_name }}/{{ item.path | regex_replace("\.j2", "") }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rw,g=r,o=r
  with_filetree: '{{ templates_source }}/oh-my-zsh'
  when:
    - item.state == 'file'
    - item.path != '.git'
    