## git role ##

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '~{{ user_name }}/{{ item.path | regex_replace("\.j2", "") }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rw,g=r,o=r
  with_filetree: '{{ templates_source }}/git'
  when:
    - item.state == 'file'
    - item.path != '.git'

- name: Ensure hooks path exists
  file:
    path: '~{{user_name}}/{{ git_config_dir }}'
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Ensure hooks templates available path exists
  file:
    path: '~{{user_name}}/{{ git_config_dir }}/templates/available/hooks'
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Clone git-good-commit hook
  git:
    repo: 'git@github.com:tommarshall/git-good-commit.git'
    dest: "~{{user_name}}/{{ git_config_dir }}/templates/available/hooks/git-good-commit"
    force: true
    accept_hostkey: true

- name: Ensure hook git-good-commit executable
  file:
    path: '~{{user_name}}/{{ git_config_dir }}/templates/available/hooks/git-good-commit/hook.sh'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rwx,g=rx,o=rx

- name: Ensure hook git-good-commit hook symlinked
  file:
    src: '~{{user_name}}/{{ git_config_dir }}/templates/available/hooks/git-good-commit/hook.sh'
    dest: '~{{user_name}}/{{ git_config_dir }}/hooks/commit-msg'
    state: link
