---
    
## services role ##

- name: Ensure directory structure exists
  file:
    path: '~{{ user_name }}/{{ item.path }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rwx,g=rx,o=rx
  with_filetree: '{{ templates_source }}/services'
  when:
    - item.state == 'directory'
    - item.path != '.git'
    - item.path != '.config'

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '~{{ user_name }}/{{ item.path | regex_replace("\.j2", "") }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u=rw,g=r,o=r
  with_filetree: '{{ templates_source }}/services'
  when:
    - item.state == 'file'
    - item.path != '.git'
